/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: allwin
* Dimensions:  56 * 20
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsallwin[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palallwin = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsallwin[0]
};

static GUI_CONST_STORAGE unsigned char acallwin[] = {
  ________, ________, ________, ________, ________, ________, ________,
  ________, _XX_____, ________, ________, ________, ________, ________,
  ________, _XX_____, ________, ________, ________, ________, ________,
  ________, XXXX____, ________, ________, ________, ________, ________,
  ________, XXXX____, ________, ________, ________, ________, ________,
  _______X, XXXXX___, ________, ________, ________, ________, ________,
  _______X, XXXXX___, _______X, XXXXXXX_, ________, ________, ________,
  ______XX, XXXXXX__, ___XXXX_, ________, XXXX____, ________, ________,
  ______XX, X__XXX__, XXX_____, ________, ____XXXX, __XXX___, ________,
  _____XXX, X__XXXXX, X_____XX, __XX____, ________, __XXX___, ________,
  _____XXX, ____XXXX, ______XX, X_XXX___, ________, __XXX___, ________,
  ____XXX_, ___XXXXX, ______XX, X_XXX___, ________, ________, ________,
  ____XXX_, _XXXXXXX, ______XX, X_XXX___, ________, ________, ________,
  ___XXXXX, XXXXXXXX, X_____XX, X_XXX_XX, __XXX__X, X_XXX_XX, XXXXXXX_,
  ___XXXXX, XX___XXX, X_____XX, X_XXX_XX, __XXX__X, X_XXX_XX, X___XXX_,
  __XXXXXX, ______XX, XX____XX, X_XXX_XX, _XXXX_XX, __XXX_XX, X___XXX_,
  __XXXXX_, ______XX, XX____XX, X_XXX_XX, XXXXXXXX, __XXX_XX, X___XXX_,
  _XXXXX__, _______X, XXX___XX, X_XXX__X, XXXXXXXX, __XXX_XX, X___XXX_,
  _XXXX___, _______X, XXX___XX, X_XXX__X, XXX_XXX_, __XXX_XX, X___XXX_,
  XXXX____, ________, XXXX__XX, X_XXX__X, XX__XXX_, __XXX_XX, X___XXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmallwin = {
  56, /* XSize */
  20, /* YSize */
  7, /* BytesPerLine */
  1, /* BitsPerPixel */
  acallwin,  /* Pointer to picture data (indices) */
  &Palallwin  /* Pointer to palette */
};

/* *** End of file *** */
