/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: logo
* Dimensions:  24 * 22
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslogo[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallogo = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorslogo[0]
};

static GUI_CONST_STORAGE unsigned char aclogo[] = {
  XXXXXXXX, XXXXXXXX, XXXXXX__,
  X_______, ________, _____X__,
  X_______, XXXXX___, _____X__,
  X_____XX, XXXXXXX_, _____X__,
  X____XXX, XXXXXXXX, _____X__,
  X___XXXX, XXXXXXXX, X____X__,
  X__XXXXX, XXXXXXXX, XX___X__,
  X__XXXXX, XXXXXXXX, XXX__X__,
  X_XXXXXX, XX______, _____X__,
  X_XXXXXX, X_______, _____X__,
  X_XXXX__, ________, _____X__,
  X_XXX___, ______XX, XXXX_X__,
  X_XX____, _______X, XXXX_X__,
  X_XX____, ________, XXX__X__,
  X__XXXXX, XXXXXXXX, XXX__X__,
  X__XXXXX, XXXXXXXX, XX___X__,
  X___XXXX, XXXXXXXX, XX___X__,
  X____XXX, XXXXXXXX, X____X__,
  X_____XX, XXXXXXX_, _____X__,
  X______X, XXXXXX__, _____X__,
  X_______, ________, _____X__,
  XXXXXXXX, XXXXXXXX, XXXXXX__
};

GUI_CONST_STORAGE GUI_BITMAP bmlogo = {
  24, /* XSize */
  22, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclogo,  /* Pointer to picture data (indices) */
  &Pallogo  /* Pointer to palette */
};

/* *** End of file *** */
