/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: up
* Dimensions:  16 * 9
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsup[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palup = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsup[0]
};

static GUI_CONST_STORAGE unsigned char acup[] = {
  _____X__, ________,
  ____XXX_, ________,
  ____XXX_, ________,
  ___XXXXX, ________,
  ___XXXXX, ________,
  __XXXXXX, X_______,
  __XXXXXX, X_______,
  _XXXXXXX, XX______,
  XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmup = {
  16, /* XSize */
  9, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  acup,  /* Pointer to picture data (indices) */
  &Palup  /* Pointer to palette */
};

/* *** End of file *** */
