/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: warning
* Dimensions:  24 * 21
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorswarning[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palwarning = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorswarning[0]
};

static GUI_CONST_STORAGE unsigned char acwarning[] = {
  ________, __XXXX__, ________,
  ________, _XXXXXX_, ________,
  ________, XXXXXXXX, ________,
  _______X, XX____XX, X_______,
  _______X, XX____XX, X_______,
  ______XX, XX____XX, XX______,
  ______XX, XX____XX, XX______,
  _____XXX, XX____XX, XXX_____,
  ____XXXX, XX____XX, XXXX____,
  ____XXXX, XX____XX, XXXX____,
  ___XXXXX, XX____XX, XXXXX___,
  ___XXXXX, XX____XX, XXXXX___,
  __XXXXXX, XX____XX, XXXXXX__,
  __XXXXXX, XXXXXXXX, XXXXXX__,
  _XXXXXXX, XXXXXXXX, XXXXXXX_,
  _XXXXXXX, XX____XX, XXXXXXX_,
  XXXXXXXX, XX____XX, XXXXXXXX,
  _XXXXXXX, XX____XX, XXXXXXX_,
  _XXXXXXX, XX____XX, XXXXXXX_,
  __XXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmwarning = {
  24, /* XSize */
  21, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acwarning,  /* Pointer to picture data (indices) */
  &Palwarning  /* Pointer to palette */
};

/* *** End of file *** */
